Repository Bisonai/orakl, pull requests merged in 2023-03, with the labels that each got.

#322 fixed slack interval and new error msg
  core/package.json
  core/src/utils.ts
Labels: bug

#332 set config minBalance in deployment scripts(vrf,request-response)
  contracts/config/baobab/request-response.json
  contracts/config/baobab/vrf.json
  contracts/config/localhost/request-response.json
  contracts/config/localhost/vrf.json
  contracts/deploy/1-RequestResponseCoordinator.ts
  contracts/deploy/2-VRFCoordinator.ts
  contracts/scripts/v0.1/types.ts
Labels: on-chain, Prepayment

#384 Setup github actions for delegator
  .github/workflows/delegator.test+build.yaml
  delegator/README.md
  delegator/src/sign/sign.service.spec.ts
  delegator/src/sign/sign.service.ts
Labels: tests, delegetor

#400 Listener setup through new `--service` param
  core/package.json
  core/src/listener/main.ts
Labels: bug

#397 Dockerize and fixed prisma setting
  api/docker-compose.build.yaml
  api/package.json
  api/prisma/schema.prisma
  api/src/Dockerfile
Labels: api

#411 Hotifx: Changed worker names to be consistent
  core/src/worker/aggregator.ts
  core/src/worker/main.ts
  core/src/worker/vrf.ts
Labels: good first issue

#393 validate `adapter` and `aggregator` throught api
  api/package.json
  api/src/adapter/adapter.controller.ts
  api/src/adapter/adapter.service.spec.ts
  api/src/adapter/adapter.service.ts
  api/src/aggregator/aggregator.controller.ts
  api/src/aggregator/aggregator.service.spec.ts
  api/src/aggregator/aggregator.service.ts
  api/src/data/data.service.spec.ts
  api/yarn.lock
  cli/.gitignore
  cli/package.json
  cli/src/adapter.ts
  cli/src/aggregator.ts
  cli/src/cli-types.ts
  cli/src/utils.ts
  core/adapter/ada-usdt.adapter.json
  core/adapter/bnb-usdt.adapter.json
  core/adapter/btc-usd.adapter.json
  core/adapter/btc-usdt.adapter.json
  core/adapter/busd-usdt.adapter.json
  core/adapter/dai-usdt.adapter.json
  core/adapter/doge-usdt.adapter.json
  core/adapter/dot-usdt.adapter.json
  core/adapter/eth-usd.adapter.json
  core/adapter/eth-usdt.adapter.json
  core/adapter/klay-usd.adapter.json
  core/adapter/klay-usdt.adapter.json
  core/adapter/matic-usdt.adapter.json
  core/adapter/shib-usdt.adapter.json
  core/adapter/sol-usdt.adapter.json
  core/adapter/trx-usdt.adapter.json
  core/adapter/usdc-usdt.adapter.json
  core/adapter/xrp-usdt.adapter.json
  core/aggregator/baobab/eth-usd.aggregator.json
  core/aggregator/localhost/ada-usdt.aggregator.json
  core/aggregator/localhost/bnb-usdt.aggregator.json
  core/aggregator/localhost/btc-usd.aggregator.json
  core/aggregator/localhost/btc-usdt.aggregator.json
  core/aggregator/localhost/busd-usdt.aggregator.json
  core/aggregator/localhost/dai-usdt.aggregator.json
  core/aggregator/localhost/doge-usdt.aggregator.json
  core/aggregator/localhost/dot-usdt.aggregator.json
  core/aggregator/localhost/eth-usd.aggregator.json
  core/aggregator/localhost/eth-usdt.aggregator.json
  core/aggregator/localhost/klay-usd.aggregator.json
  core/aggregator/localhost/klay-usdt.aggregator.json
  core/aggregator/localhost/matic-usdt.aggregator.json
  core/aggregator/localhost/shib-usdt.aggregator.json
  core/aggregator/localhost/sol-usdt.aggregator.json
  core/aggregator/localhost/trx-usdt.aggregator.json
  core/aggregator/localhost/usdc-usdt.aggregator.json
  core/aggregator/localhost/xrp-usdt.aggregator.json
  docs/v0.1-internal/data-feed.md
  fetcher/README.md
Labels: off-chain, cli, api, data-fetcher

#443 Migrate docker-hub to ECR using git-action
  .github/workflows/api.image+upload.yaml
  .github/workflows/cli.image+upload.yaml
  .github/workflows/core.image+upload.yaml
  .github/workflows/fetcher.image+upload.yaml
  api/docker-compose.build.yaml
  cli/docker-compose.build.yaml
  core/docker-compose.build.yaml
  fetcher/docker-compose.build.yaml
Labels: infra

#445 readme fixed & redis client connect with host:port in initial stage
  contracts/README.md
  core/src/listener/main.ts
  core/src/reporter/main.ts
Labels: bug
