Repository Bisonai/orakl, pull requests merged in 2023-02, with the labels that each got.

#272 remove OZ AccessControl from prepayment
  contracts/src/v0.1/Prepayment.sol
  contracts/test/v0.1/Prepayment.test.ts
Labels: on-chain

#279 add `BTC/USD`, `ETH/USD` data feeds
  core/adapter/btc-usd.adapter.json
  core/adapter/eth-usd.adapter.json
  core/aggregator/btc-usd.aggregator.json
  core/aggregator/eth-usd.aggregator.json
  core/aggregator/klay-usd.adapter.json
  core/aggregator/klay-usd.aggregator.json
  core/src/worker/reducer.ts
Labels: off-chain

#282 fixed dockerfile and add previous pushed version of image
  core/docker-compose.build.yaml
  core/src/Dockerfile.dev
Labels: bug

#287 hotfix for ORAKL_DIR settings ENV for docker image or Kubernetes
  core/src/cli/orakl-cli/src/index.ts
Labels: cli

#292 adjsut maxGasLimit to 2500000
  contracts/config/baobab/request-response.json
  contracts/config/baobab/vrf.json
  contracts/config/localhost/request-response.json
  contracts/config/localhost/vrf.json
  contracts/test/v0.1/RequestResponse.config.ts
  contracts/test/v0.1/VRF.config.ts
Labels: vrf, request-response

#289 add caver-js test
  .github/workflows/cli.build+publish.yaml
  .github/workflows/core.test+build.yaml
  core/package.json
  core/test/caver-js.test.ts
  core/yarn.lock
Labels: off-chain

#313 Integration test for VRF
  .github/workflows/vrf.integration.test.yaml
  contracts/scripts/v0.1/vrf/integration/read-vrf.ts
  contracts/scripts/v0.1/vrf/integration/request-vrf.ts
  core/src/settings.ts
  core/test/cli-adapter.ts
  core/test/cli-aggregator.ts
  core/test/cli-chain.test.ts
  core/test/cli-kv.test.ts
  core/test/cli-listener.test.ts
  core/test/cli-service.test.ts
  core/test/cli-vrf.test.ts
Labels: on-chain, off-chain, vrf
