Repository Bisonai/orakl, pull requests merged in 2023-07, with the labels that each got.

#757 Add monitor API to notify each account if they have a low balance amount
  monitor/.env.example
  monitor/migrations/1676548185141_create_initial_tables.ts
  monitor/migrations/1689582056679_alter-account-index-drop.ts
  monitor/migrations/1689584863425_alter-set-balance-primary-key.ts
  monitor/migrations/1689585197164_alter-add-column-balance-alarm-amount.ts
  monitor/package.json
  monitor/src/accounts/accounts.repository.ts
  monitor/src/accounts/accounts.service.ts
  monitor/src/accounts/dto/account.dto.ts
  monitor/src/accounts/dto/balance.dto.ts
Labels: enhancement

#763 [HOTFIX] Add migrations into the dockerfile
  monitor/Dockerfile
Labels: deployment

#768 Increase orakl contract package version to include Registry, and L2Endpoint
  contracts/deploy/Registry/Registry.cjs
  contracts/package.json
  contracts/scripts/v0.1/registry/proposeChain.cjs
Labels: L2
